name: info

on:
  push:
  workflow_dispatch:

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: ps
        run: |
          (
            echo '<details><summary>ps</summary>'
            echo
            echo '```'
            ps aux
            echo '```'
            echo '</details>'
          ) >> $GITHUB_STEP_SUMMARY

      - name: systemctl
        run: |
          (
            echo '<details><summary>systemctl</summary>'
            echo
            echo '```'
            systemctl --type=service --state=running | cat
            echo '```'
            echo '</details>'
          ) >> $GITHUB_STEP_SUMMARY

      - name: free
        run: |
          (
            echo '## free'
            echo '```'
            free -h
            free
            echo '```'
          ) >> $GITHUB_STEP_SUMMARY
      
      - name: stop services
        run: |
          (
            echo '## systemctl stop ...'
            echo '```'
            sudo systemctl disable php8.1-fpm mono-xsp4 walinuxagent multipathd walinuxagent chrony cron getty@tty1 networkd-dispatcher rsyslog serial-getty@ttyS0 snapd multipathd.socket snapd.socket
            sudo systemctl stop php8.1-fpm mono-xsp4 walinuxagent multipathd walinuxagent chrony cron getty@tty1 networkd-dispatcher rsyslog serial-getty@ttyS0 snapd
            sudo killall mono
            echo '```'
          ) >> $GITHUB_STEP_SUMMARY

      - name: free
        run: |
          (
            echo '## free'
            echo '```'
            free -h
            free
            echo '```'
          ) >> $GITHUB_STEP_SUMMARY
      
      - name: ps
        run: |
          (
            echo '<details><summary>ps</summary>'
            echo
            echo '```'
            ps aux
            echo '```'
            echo '</details>'
          ) >> $GITHUB_STEP_SUMMARY

      - name: systemctl
        run: |
          (
            echo '<details><summary>systemctl</summary>'
            echo
            echo '```'
            systemctl --type=service --state=running | cat
            echo '```'
            echo '</details>'
          ) >> $GITHUB_STEP_SUMMARY

      - name: pstree
        run: |
          (
            echo '<details><summary>pstree</summary>'
            echo
            echo '```'
            sudo pstree -a -S -t -u -Z
            echo '```'
            echo '</details>'
          ) >> $GITHUB_STEP_SUMMARY

      - name: check swap
        run: |
          (
            echo '## check swap'
            echo '```'
            swapon -s
            cat /proc/swaps
            echo '```'
          ) >> $GITHUB_STEP_SUMMARY

      - name: disks
        run: |
          (
            echo '## df'
            echo '```'
            df
            echo '```'
          ) >> $GITHUB_STEP_SUMMARY

      - name: enable swap
        run: |
          (
            echo '## enable swap'
            echo '```'
            sudo fallocate -l 10G /mnt/big-swapfile
            sudo chmod 600 /mnt/big-swapfile
            sudo mkswap /mnt/big-swapfile
            sudo swapon /mnt/big-swapfile
            echo '```'
          ) >> $GITHUB_STEP_SUMMARY

      - name: check swap
        run: |
          (
            echo '## check swap'
            echo '```'
            swapon -s
            cat /proc/swaps
            echo '```'
          ) >> $GITHUB_STEP_SUMMARY

      - name: disks
        run: |
          (
            echo '## df'
            echo '```'
            df
            echo '```'
          ) >> $GITHUB_STEP_SUMMARY

      - name: free
        run: |
          (
            echo '## free'
            echo '```'
            free -h
            free
            echo '```'
          ) >> $GITHUB_STEP_SUMMARY
