name: info

on:
  push:
  workflow_dispatch:

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: ps
        run: |
          (
            echo '## ps'
            echo '```'
            ps aux
            echo '```'
          ) >> $GITHUB_STEP_SUMMARY

      - name: systemctl
        run: |
          (
            echo '## systemctl'
            echo '```'
            systemctl --type=service --state=running | cat
            echo '```'
          ) >> $GITHUB_STEP_SUMMARY

      - name: free
        run: |
          (
            echo '## free'
            echo '```'
            free -h
            echo '```'
          ) >> $GITHUB_STEP_SUMMARY
      
      - name: stop services
        run: |
          (
            echo '## systemctl stop ...'
            echo '```'
            sudo systemctl stop php8.1-fpm mono-xsp4 walinuxagent multipathd walinuxagent runner-provisioner
            echo '```'
          ) >> $GITHUB_STEP_SUMMARY

      - name: free
        run: |
          (
            echo '## free'
            echo '```'
            free -h
            echo '```'
          ) >> $GITHUB_STEP_SUMMARY
      
