name: info

on:
  push:
  workflow_dispatch:

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: ps
        run: |
          (
            echo '## ps'
            echo '```'
            ps aux
            echo '```'
          ) >> $GITHUB_STEP_SUMMARY

      - name: systemctl
        run: |
          (
            echo '## systemctl'
            echo '```'
            systemctl | cat
            echo '```'
          ) >> $GITHUB_STEP_SUMMARY

      - name: free
        run: |
          (
            echo '## free'
            echo '```'
            free -h
            echo '```'
          ) >> $GITHUB_STEP_SUMMARY
      
      - name: stop php
        run: |
          (
            echo '## systemctl stop php'
            echo '```'
            sudo systemctl stop php8.1-fpm.service
            echo '```'
          ) >> $GITHUB_STEP_SUMMARY

      - name: free
        run: |
          (
            echo '## free'
            echo '```'
            free -h
            echo '```'
          ) >> $GITHUB_STEP_SUMMARY
      
